default["app"]["path"] = "/var/www/app.dev"
default["app"]["project_dir"] = "app"
default["app"]["public_dir"] = "public"
default["app"]["source_folder"] = "defualt"
default["app"]["private_dir"] = "null"
default["app"]["server_name"] = "app.dev"
default["app"]["server_alias"] = "null"
default["app"]["cert_name"] = "null"
default["app"]["cert_path"] = "/etc/ssl/certs/"
default["app"]["key_name"] = "null"
default["app"]["key_path"] = "/etc/ssl/private/"
default["app"]["chainfile_name"] = "null"
default["app"]["chainfile_path"] = "null"
default["app"]["composer_support"] = "null"

# app2
default["app2"]["path"] = "/var/www/app2.dev"
default["app2"]["project_dir"] = "app2"
default["app2"]["public_dir"] = "public"
default["app2"]["source_folder"] = "defualt"
default["app2"]["private_dir"] = "null"
default["app2"]["server_name"] = "app2.dev"
default["app2"]["server_alias"] = "null"
default["app2"]["cert_name"] = "null"
default["app2"]["cert_path"] = "/etc/ssl/certs/"
default["app2"]["key_name"] = "null"
default["app2"]["key_path"] = "/etc/ssl/private/"
default["app2"]["composer_support"] = "null"

